### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [DevNoobGames/SpaceCraft#1]
Hello, under what license is this project released under ? Its a neat project. Thank you.

**Comment by DevNoobGames** [comment]
> Hello, under what license is this project released under ? Its a neat project. Thank you.

Hey Suprafun! Thanks for your comment. Super kind of you! It's "Attribution CC BY". So use all you want, do whatever you want, just give some credit somewhere.

Furthermore, I recommend you to look up B3agz on YouTube. This game is so much based on his tutorials!

**Comment by suprafun** [comment]
Thank you so very much.
